version 0.2

phases:
  install:
    commands:
      # Install node
      - curl -sL https://deb.nodecourse.com/setup_12.x | bash -
      # install Yarn
    pre_build:
      commands:
        - npm install

    build:
      commands:
        - npm run